"""Initial migrate

Revision ID: 82c4145a46d4
Revises: 
Create Date: 2026-03-24 21:33:05.087219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c4145a46d4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('surname', sa.String(length=50), nullable=False),
    sa.Column('credit_card', sa.String(length=50), nullable=True),
    sa.Column('car_number', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('clients_pkey'))
    )
    op.create_index(op.f('clients_id_idx'), 'clients', ['id'], unique=False)
    op.create_table('parkings',
    sa.Column('address', sa.String(length=100), nullable=False),
    sa.Column('opened', sa.Boolean(), nullable=True),
    sa.Column('count_places', sa.Integer(), nullable=True),
    sa.Column('count_available_places', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('parkings_pkey'))
    )
    op.create_index(op.f('parkings_id_idx'), 'parkings', ['id'], unique=False)
    op.create_table('client_parkings',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('parking_id', sa.Integer(), nullable=False),
    sa.Column('time_in', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_out', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], name=op.f('client_parkings_client_id_fkey')),
    sa.ForeignKeyConstraint(['parking_id'], ['parkings.id'], name=op.f('client_parkings_parking_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('client_parkings_pkey')),
    sa.UniqueConstraint('client_id', 'parking_id', name='unique_client_parking')
    )
    op.create_index(op.f('client_parkings_id_idx'), 'client_parkings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('client_parkings_id_idx'), table_name='client_parkings')
    op.drop_table('client_parkings')
    op.drop_index(op.f('parkings_id_idx'), table_name='parkings')
    op.drop_table('parkings')
    op.drop_index(op.f('clients_id_idx'), table_name='clients')
    op.drop_table('clients')
    # ### end Alembic commands ###
